# Generated by Django 4.2.7 on 2024-02-04 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genericviewsDemo", "0002_country_movies_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1875),
                    django.core.validators.MaxValueValidator(2027),
                ]
            ),
        ),
    ]
