# Generated by Django 5.0.2 on 2024-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kaczacze", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wpis",
            name="time",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
