# Generated by Django 4.2.7 on 2024-02-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kaczacze", "0006_alter_komentarz_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="komentarz",
            name="content",
            field=models.CharField(max_length=100),
        ),
    ]
