# Generated by Django 4.2.7 on 2024-02-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kaczacze", "0002_wpis_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="komentarz",
            name="wpis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="komentarze",
                to="kaczacze.wpis",
            ),
        ),
    ]
