# Generated by Django 4.2.7 on 2024-02-08 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("kaczacze", "0003_alter_komentarz_wpis"),
    ]

    operations = [
        migrations.AddField(
            model_name="komentarz",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="komentarz",
            name="time",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="komentarz",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="wpis",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
