# Generated by Django 4.2.7 on 2024-02-08 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kaczacze", "0005_alter_komentarz_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="komentarz",
            name="content",
            field=models.CharField(
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
